agent:
  thread_count: 4
  server_url: https://localhost:27000
  retry_interval: 30s
  verification_mode: none # TODO: change this setting to full
events:
  batch_interval: 10s
  batch_size: 1MB
inventory:
  enabled: true
  interval: 1h
  scan_on_start: true
  hardware: true
  system: true
  networks: true
  packages: true
  ports: true
  ports_all: true
  processes: true
  hotfixes: true
logcollector:
  enabled: true
  localfiles:
    - /var/log/auth.log
  reload_interval: 1m
  file_wait: 500ms
  windows:
    - channel: Application
      query: Event[System/EventID = 4624]
      use-bookmark: true
      reconnect-time: 5s
    - channel: System
      query: Event[System/EventID = 7040]
      use-bookmark: false
      reconnect-time: 5s
